### ISSUE TITLE
Enchantment Compatibility prevents applying enchantments on certain modded items, even if they are not blacklisted

### ISSUE THREAD

**Issue by RecyclingTiger** [Fuzss/sneakycurses#13]
When Enchantment Compatibility is active, some non-sword weapons like the naga fang dagger from Mowzies Mobs or the skillet from Farmer's Delight cannot recieve vanilla enchantments except unbreaking and mending.

**Comment by Fuzss** [comment]
The problem here is that these items check for some specific enchantment categories when deciding if the enchantment is valid. But I replace nearly all enchantment categories to allow this custom behaviour so that enchantments can be applied to more items. 

The only solution I can think of is to allow defining additional enchantments for modded items, although I‘m not sure how the configuration for that would look exactly.

**Comment by Fuzss** [comment]
Alright, so this portion of Sneaky Magic has been moved to a separate mod: [Universal Enchants](https://www.curseforge.com/minecraft/mc-mods/universal-enchants-forge).

For that mod I've just pushed a new version that fully supports those kind of custom weapons. It's 1.19+ only though, I won't be backporting the new system.
